### ISSUE TITLE
UHI-EP: return np.ndarray from .values(), .variances(), and .counts()

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/uhi#10]
The three return values should be np.ndarray; now that NumPy supports typing, ArrayLike is too broad; all returns should be np.ndarrays or subclasses. And the current definition is a little too simple anyway, a 2D array isn't exactly a sequence of floats. @HDembinski @jpivarski I need signoff from you for significant changes, this is _just_ large enough to ask for one.

**Comment by jpivarski** [comment]
Being able to reference an `np.ndarray` as a type might require a specific version of NumPy to check it, but not for simply defining the protocol and testing it in some version.

As another thing to consider: would we want it to be legal for some implementation to return a CuPy array, JAX DeviceArray, PyTorch Tensor, etc.? Would making the return type `np.ndarray` prohibit that? If that's a consideration, [data-apis.org](https://data-apis.org/) might be defining some types with the appropriate level of abstraction.

Other than that, I have no objection to narrowing the return type. Uproot produces `np.ndarray`, so that wouldn't be an issue.

**Comment by henryiii** [comment]
It doesn't require 1.20 to check specifically, but it's pretty useless before 1.20, because it types as "Any" before then (any untyped package is just all Anys). But checking needs to set numpy 1.20 anyway; and that's not a problem, a user who knows how to type check knows how to pin versions for the type check. Usually in a pre-commit step. :)

Yes, I briefly thought of this, and np.ndarray would prohibit returning anything that is not a np.ndarray subclass. We could always broaden the return a bit if someone really needed a CUDA array or the like - though I'm not sure those would ever be needed for plotting; not sure about fitting. All existing users return np.ndarray, and I'd expect that's what's expected for almost any plotter.

**Comment by HDembinski** [comment]
Restricting it to ndarray is probably ok.
