### ISSUE TITLE
UHI-EP: make PlottableAxisGeneric a Sequence?

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/uhi#6]
This may be me misunderstanding protocols, but PlottableAxisGeneric is not defined as a sequence, though it implements the necessary functions to satisfy `collections.abc.Sequence`. Is it implied that `iter(axis)` is available based on the current definition?

**Comment by nsmith-** [comment]
Thanks for the usage link, this helps. Should we leave this open to consider upgrading to `Sequence` at some point?

**Comment by jpivarski** [comment]
My argument might have been that Sequence creates `__contains__`, `__iter__`, `__reversed__`, `index`, and `count` methods, which are sometimes not wanted.

For a PlottableAxisGeneric, I don't see a reason to not want one of those methods. I emphatically didn't want them for `ak.Array` (`__contains__`, `index`, and `count` assume you have an equality operation that returns `True` or `False` for the items, which isn't true of NumPy-like arrays), but these arguments don't apply to an axis, since an axis is like a _one-dimensional_ array whose items are numbers, strings, or 2-tuples.

In fact, look at this:

https://github.com/scikit-hep/uproot4/blob/afaaf7d242df529d5bf5c69ebf85cd2c6ec3ad9b/uproot/behaviors/TAxis.py#L48

an Uproot TAxis is a Sequence. That was going beyond what the protocol required, but I didn't see a problem with it.

**Comment by henryiii** [comment]
The other implementations are Sequences too; boost-histogram uses a customized Tuple. The general idea is this would be a tuple or a list, or maybe a NumPy array; all of which are Sequences. I'm mildly +1 on making this a Sequence. `__iter__` certainly could be useful to be able to count on.
